<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Points Counter Copyright</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css">
        <link rel="stylesheet" href="/style.css">
    </head>
    <body>
        <h1 class="title center">Points Counter Copyright</h1>
        <p class="small center">Version ${d.version}</p>
        <hr>
        <div class="nav">
            <div class="item">
                <a href="/" class="center">Home</a>
            </div>
            <div class="item">
                <a href="/commands">Commands</a>
            </div>
            <div class="item">
                <a href="/tech-specs">Technical</a>
            </div>
        </div>
        <hr>
        This bot is open source under the
        <a
            href="https://github.com/Tyler-A/points_counter/blob/master/LICENSE"
            target="_blank"
            >GNU GPL 3.0 License</a
        >
    </body>
</html>