<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Points Counter Copyright</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css">
        <link rel="stylesheet" href="/style.css">
    </head>
    <body>
        <h1 class="title center">Points Counter Copyright</h1>
        <p class="small center">Version ${d.c.bot.VERSION}</p>
        <hr>
        <div class="nav">
            <div class="item">
                <a href="/" class="center">Home</a>
            </div>
            <div class="item">
                <a href="/commands">Commands</a>
            </div>
            <div class="item">
                <a href="/tech-specs">Technical</a>
            </div>
        </div>
        <hr>
        This bot was written for Resonym's Twitch stream on behalf of Tyler Akins, all rights remain under Canadian Copyright Law with Tyler Akins as their rightful owner.
    </body>
</html>