<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Points Counter Help</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css">
        <link rel="stylesheet" href="/style.css">
    </head>
    <body>
        <div class="alert error">
            <h2 class="title center">Error 404:</h2>
            <p>
                Cannot get requested resource. No command by name of
                <code>${d.command}</code> could be found.
                <br>
                <br>
                <a href="/">Return Home</a>
            </p>
        </div>
    </body>
</html>